#ifndef __MODELDB_H
#define __MODELDB_H


#if defined TARGET_MODEL_IAP15F105                              \
    || defined TARGET_MODEL_IAP15F105W                          \
    || defined TARGET_MODEL_IAP15L105                           \
    || defined TARGET_MODEL_IAP15L105W                          \
    || defined TARGET_MODEL_STC15F100                           \
    || defined TARGET_MODEL_STC15F100W                          \
    || defined TARGET_MODEL_STC15F101                           \
    || defined TARGET_MODEL_STC15F101W                          \
    || defined TARGET_MODEL_STC15F102                           \
    || defined TARGET_MODEL_STC15F102W                          \
    || defined TARGET_MODEL_STC15F103                           \
    || defined TARGET_MODEL_STC15F103W                          \
    || defined TARGET_MODEL_STC15F104                           \
    || defined TARGET_MODEL_STC15F104E                          \
    || defined TARGET_MODEL_STC15F104W                          \
    || defined TARGET_MODEL_STC15L100                           \
    || defined TARGET_MODEL_STC15L100W                          \
    || defined TARGET_MODEL_STC15L101                           \
    || defined TARGET_MODEL_STC15L101W                          \
    || defined TARGET_MODEL_STC15L102                           \
    || defined TARGET_MODEL_STC15L102W                          \
    || defined TARGET_MODEL_STC15L103                           \
    || defined TARGET_MODEL_STC15L103W                          \
    || defined TARGET_MODEL_STC15L104                           \
    || defined TARGET_MODEL_STC15L104E                          \
    || defined TARGET_MODEL_STC15L104W
#define TARGET_FAMILY_STC15F10
#endif

#if defined TARGET_MODEL_IAP15F105                              \
    || defined TARGET_MODEL_IAP15F105W                          \
    || defined TARGET_MODEL_IAP15F1K61AS                        \
    || defined TARGET_MODEL_IAP15F1K61S                         \
    || defined TARGET_MODEL_IAP15F1K61S2                        \
    || defined TARGET_MODEL_IAP15F205EA                         \
    || defined TARGET_MODEL_IAP15F2K61AS                        \
    || defined TARGET_MODEL_IAP15F2K61S                         \
    || defined TARGET_MODEL_IAP15F2K61S2                        \
    || defined TARGET_MODEL_IAP15F413AD                         \
    || defined TARGET_MODEL_IAP15L105                           \
    || defined TARGET_MODEL_IAP15L105W                          \
    || defined TARGET_MODEL_IAP15L1K61AS                        \
    || defined TARGET_MODEL_IAP15L1K61S                         \
    || defined TARGET_MODEL_IAP15L1K61S2                        \
    || defined TARGET_MODEL_IAP15L205EA                         \
    || defined TARGET_MODEL_IAP15L2K61AS                        \
    || defined TARGET_MODEL_IAP15L2K61S                         \
    || defined TARGET_MODEL_IAP15L2K61S2                        \
    || defined TARGET_MODEL_IAP15L413AD                         \
    || defined TARGET_MODEL_IAP15W105                           \
    || defined TARGET_MODEL_IAP15W105S                          \
    || defined TARGET_MODEL_IAP15W105SW                         \
    || defined TARGET_MODEL_IAP15W1K29S                         \
    || defined TARGET_MODEL_IAP15W205S                          \
    || defined TARGET_MODEL_IAP15W413AS                         \
    || defined TARGET_MODEL_IAP15W413S                          \
    || defined TARGET_MODEL_IAP15W4K58S4                        \
    || defined TARGET_MODEL_IAP15W4K61S4                        \
    || defined TARGET_MODEL_STC15F100                           \
    || defined TARGET_MODEL_STC15F100W                          \
    || defined TARGET_MODEL_STC15F101                           \
    || defined TARGET_MODEL_STC15F101W                          \
    || defined TARGET_MODEL_STC15F102                           \
    || defined TARGET_MODEL_STC15F102W                          \
    || defined TARGET_MODEL_STC15F103                           \
    || defined TARGET_MODEL_STC15F103W                          \
    || defined TARGET_MODEL_STC15F104                           \
    || defined TARGET_MODEL_STC15F104E                          \
    || defined TARGET_MODEL_STC15F104W                          \
    || defined TARGET_MODEL_STC15F1K08AS                        \
    || defined TARGET_MODEL_STC15F1K08S                         \
    || defined TARGET_MODEL_STC15F1K08S2                        \
    || defined TARGET_MODEL_STC15F1K16AS                        \
    || defined TARGET_MODEL_STC15F1K16S                         \
    || defined TARGET_MODEL_STC15F1K16S2                        \
    || defined TARGET_MODEL_STC15F1K24AS                        \
    || defined TARGET_MODEL_STC15F1K24S                         \
    || defined TARGET_MODEL_STC15F1K24S2                        \
    || defined TARGET_MODEL_STC15F1K32AS                        \
    || defined TARGET_MODEL_STC15F1K32S                         \
    || defined TARGET_MODEL_STC15F1K32S2                        \
    || defined TARGET_MODEL_STC15F1K40AS                        \
    || defined TARGET_MODEL_STC15F1K40S                         \
    || defined TARGET_MODEL_STC15F1K40S2                        \
    || defined TARGET_MODEL_STC15F1K48AS                        \
    || defined TARGET_MODEL_STC15F1K48S                         \
    || defined TARGET_MODEL_STC15F1K48S2                        \
    || defined TARGET_MODEL_STC15F1K56AS                        \
    || defined TARGET_MODEL_STC15F1K56S                         \
    || defined TARGET_MODEL_STC15F1K56S2                        \
    || defined TARGET_MODEL_STC15F1K60AS                        \
    || defined TARGET_MODEL_STC15F1K60S                         \
    || defined TARGET_MODEL_STC15F1K60S2                        \
    || defined TARGET_MODEL_STC15F204EA                         \
    || defined TARGET_MODEL_STC15F2K                            \
    || defined TARGET_MODEL_STC15F2K08AS                        \
    || defined TARGET_MODEL_STC15F2K08S                         \
    || defined TARGET_MODEL_STC15F2K08S2                        \
    || defined TARGET_MODEL_STC15F2K16AS                        \
    || defined TARGET_MODEL_STC15F2K16S                         \
    || defined TARGET_MODEL_STC15F2K16S2                        \
    || defined TARGET_MODEL_STC15F2K24AS                        \
    || defined TARGET_MODEL_STC15F2K24S                         \
    || defined TARGET_MODEL_STC15F2K24S2                        \
    || defined TARGET_MODEL_STC15F2K32AS                        \
    || defined TARGET_MODEL_STC15F2K32S                         \
    || defined TARGET_MODEL_STC15F2K32S2                        \
    || defined TARGET_MODEL_STC15F2K40AS                        \
    || defined TARGET_MODEL_STC15F2K40S                         \
    || defined TARGET_MODEL_STC15F2K40S2                        \
    || defined TARGET_MODEL_STC15F2K48AS                        \
    || defined TARGET_MODEL_STC15F2K48S                         \
    || defined TARGET_MODEL_STC15F2K48S2                        \
    || defined TARGET_MODEL_STC15F2K56AS                        \
    || defined TARGET_MODEL_STC15F2K56S                         \
    || defined TARGET_MODEL_STC15F2K56S2                        \
    || defined TARGET_MODEL_STC15F2K60AS                        \
    || defined TARGET_MODEL_STC15F2K60S                         \
    || defined TARGET_MODEL_STC15F2K60S2                        \
    || defined TARGET_MODEL_STC15F404AD                         \
    || defined TARGET_MODEL_STC15F408AD                         \
    || defined TARGET_MODEL_STC15F412AD                         \
    || defined TARGET_MODEL_STC15L100                           \
    || defined TARGET_MODEL_STC15L100W                          \
    || defined TARGET_MODEL_STC15L101                           \
    || defined TARGET_MODEL_STC15L101W                          \
    || defined TARGET_MODEL_STC15L102                           \
    || defined TARGET_MODEL_STC15L102W                          \
    || defined TARGET_MODEL_STC15L103                           \
    || defined TARGET_MODEL_STC15L103W                          \
    || defined TARGET_MODEL_STC15L104                           \
    || defined TARGET_MODEL_STC15L104E                          \
    || defined TARGET_MODEL_STC15L104W                          \
    || defined TARGET_MODEL_STC15L1K08AS                        \
    || defined TARGET_MODEL_STC15L1K08S                         \
    || defined TARGET_MODEL_STC15L1K08S2                        \
    || defined TARGET_MODEL_STC15L1K16AS                        \
    || defined TARGET_MODEL_STC15L1K16S                         \
    || defined TARGET_MODEL_STC15L1K16S2                        \
    || defined TARGET_MODEL_STC15L1K24AS                        \
    || defined TARGET_MODEL_STC15L1K24S                         \
    || defined TARGET_MODEL_STC15L1K24S2                        \
    || defined TARGET_MODEL_STC15L1K32AS                        \
    || defined TARGET_MODEL_STC15L1K32S                         \
    || defined TARGET_MODEL_STC15L1K32S2                        \
    || defined TARGET_MODEL_STC15L1K40AS                        \
    || defined TARGET_MODEL_STC15L1K40S                         \
    || defined TARGET_MODEL_STC15L1K40S2                        \
    || defined TARGET_MODEL_STC15L1K48AS                        \
    || defined TARGET_MODEL_STC15L1K48S                         \
    || defined TARGET_MODEL_STC15L1K48S2                        \
    || defined TARGET_MODEL_STC15L1K56AS                        \
    || defined TARGET_MODEL_STC15L1K56S                         \
    || defined TARGET_MODEL_STC15L1K56S2                        \
    || defined TARGET_MODEL_STC15L1K60AS                        \
    || defined TARGET_MODEL_STC15L1K60S                         \
    || defined TARGET_MODEL_STC15L1K60S2                        \
    || defined TARGET_MODEL_STC15L204EA                         \
    || defined TARGET_MODEL_STC15L2K08AS                        \
    || defined TARGET_MODEL_STC15L2K08S                         \
    || defined TARGET_MODEL_STC15L2K08S2                        \
    || defined TARGET_MODEL_STC15L2K16AS                        \
    || defined TARGET_MODEL_STC15L2K16S                         \
    || defined TARGET_MODEL_STC15L2K16S2                        \
    || defined TARGET_MODEL_STC15L2K24AS                        \
    || defined TARGET_MODEL_STC15L2K24S                         \
    || defined TARGET_MODEL_STC15L2K24S2                        \
    || defined TARGET_MODEL_STC15L2K32AS                        \
    || defined TARGET_MODEL_STC15L2K32S                         \
    || defined TARGET_MODEL_STC15L2K32S2                        \
    || defined TARGET_MODEL_STC15L2K40AS                        \
    || defined TARGET_MODEL_STC15L2K40S                         \
    || defined TARGET_MODEL_STC15L2K40S2                        \
    || defined TARGET_MODEL_STC15L2K48AS                        \
    || defined TARGET_MODEL_STC15L2K48S                         \
    || defined TARGET_MODEL_STC15L2K48S2                        \
    || defined TARGET_MODEL_STC15L2K56AS                        \
    || defined TARGET_MODEL_STC15L2K56S                         \
    || defined TARGET_MODEL_STC15L2K56S2                        \
    || defined TARGET_MODEL_STC15L2K60AS                        \
    || defined TARGET_MODEL_STC15L2K60S                         \
    || defined TARGET_MODEL_STC15L2K60S2                        \
    || defined TARGET_MODEL_STC15L404AD                         \
    || defined TARGET_MODEL_STC15L408AD                         \
    || defined TARGET_MODEL_STC15L412AD                         \
    || defined TARGET_MODEL_STC15W100                           \
    || defined TARGET_MODEL_STC15W101                           \
    || defined TARGET_MODEL_STC15W101S                          \
    || defined TARGET_MODEL_STC15W101SW                         \
    || defined TARGET_MODEL_STC15W102                           \
    || defined TARGET_MODEL_STC15W102S                          \
    || defined TARGET_MODEL_STC15W102SW                         \
    || defined TARGET_MODEL_STC15W103                           \
    || defined TARGET_MODEL_STC15W103S                          \
    || defined TARGET_MODEL_STC15W103SW                         \
    || defined TARGET_MODEL_STC15W104                           \
    || defined TARGET_MODEL_STC15W104S                          \
    || defined TARGET_MODEL_STC15W104SW                         \
    || defined TARGET_MODEL_STC15W1K08PWM                       \
    || defined TARGET_MODEL_STC15W1K16PWM                       \
    || defined TARGET_MODEL_STC15W1K16S                         \
    || defined TARGET_MODEL_STC15W1K20AS                        \
    || defined TARGET_MODEL_STC15W1K20S                         \
    || defined TARGET_MODEL_STC15W1K24S                         \
    || defined TARGET_MODEL_STC15W1K32AS                        \
    || defined TARGET_MODEL_STC15W1K48AS                        \
    || defined TARGET_MODEL_STC15W201S                          \
    || defined TARGET_MODEL_STC15W202S                          \
    || defined TARGET_MODEL_STC15W203S                          \
    || defined TARGET_MODEL_STC15W204S                          \
    || defined TARGET_MODEL_STC15W2K32AS                        \
    || defined TARGET_MODEL_STC15W2K32S2                        \
    || defined TARGET_MODEL_STC15W2K48AS                        \
    || defined TARGET_MODEL_STC15W2K48S2                        \
    || defined TARGET_MODEL_STC15W401AS                         \
    || defined TARGET_MODEL_STC15W402AS                         \
    || defined TARGET_MODEL_STC15W404AS                         \
    || defined TARGET_MODEL_STC15W404S                          \
    || defined TARGET_MODEL_STC15W408AS                         \
    || defined TARGET_MODEL_STC15W408S                          \
    || defined TARGET_MODEL_STC15W410AS                         \
    || defined TARGET_MODEL_STC15W410S                          \
    || defined TARGET_MODEL_STC15W412AS                         \
    || defined TARGET_MODEL_STC15W412S                          \
    || defined TARGET_MODEL_STC15W4K                            \
    || defined TARGET_MODEL_STC15W4K16S4                        \
    || defined TARGET_MODEL_STC15W4K24S4                        \
    || defined TARGET_MODEL_STC15W4K32S4                        \
    || defined TARGET_MODEL_STC15W4K40S4                        \
    || defined TARGET_MODEL_STC15W4K48S4                        \
    || defined TARGET_MODEL_STC15W4K56S4
#define TARGET_FAMILY_STC15F
#endif

#if defined TARGET_MODEL_STC12C5201                             \
    || defined TARGET_MODEL_STC12C5201AD                        \
    || defined TARGET_MODEL_STC12C5201PWM                       \
    || defined TARGET_MODEL_STC12C5202                          \
    || defined TARGET_MODEL_STC12C5202AD                        \
    || defined TARGET_MODEL_STC12C5202PWM                       \
    || defined TARGET_MODEL_STC12C5203                          \
    || defined TARGET_MODEL_STC12C5203AD                        \
    || defined TARGET_MODEL_STC12C5203PWM                       \
    || defined TARGET_MODEL_STC12C5204                          \
    || defined TARGET_MODEL_STC12C5204AD                        \
    || defined TARGET_MODEL_STC12C5204PWM                       \
    || defined TARGET_MODEL_STC12C5205                          \
    || defined TARGET_MODEL_STC12C5205AD                        \
    || defined TARGET_MODEL_STC12C5205PWM                       \
    || defined TARGET_MODEL_STC12C5206                          \
    || defined TARGET_MODEL_STC12C5206AD                        \
    || defined TARGET_MODEL_STC12C5206PWM                       \
    || defined TARGET_MODEL_STC12LE5201                         \
    || defined TARGET_MODEL_STC12LE5201AD                       \
    || defined TARGET_MODEL_STC12LE5201PWM                      \
    || defined TARGET_MODEL_STC12LE5202                         \
    || defined TARGET_MODEL_STC12LE5202AD                       \
    || defined TARGET_MODEL_STC12LE5202PWM                      \
    || defined TARGET_MODEL_STC12LE5203                         \
    || defined TARGET_MODEL_STC12LE5203AD                       \
    || defined TARGET_MODEL_STC12LE5203PWM                      \
    || defined TARGET_MODEL_STC12LE5204                         \
    || defined TARGET_MODEL_STC12LE5204AD                       \
    || defined TARGET_MODEL_STC12LE5204PWM                      \
    || defined TARGET_MODEL_STC12LE5205                         \
    || defined TARGET_MODEL_STC12LE5205AD                       \
    || defined TARGET_MODEL_STC12LE5205PWM                      \
    || defined TARGET_MODEL_STC12LE5206                         \
    || defined TARGET_MODEL_STC12LE5206AD                       \
    || defined TARGET_MODEL_STC12LE5206PWM
#define TARGET_FAMILY_STC12C52
#endif

#if defined TARGET_MODEL_IAP12C5A08                             \
    || defined TARGET_MODEL_IAP12C5A08AD                        \
    || defined TARGET_MODEL_IAP12C5A08CCP                       \
    || defined TARGET_MODEL_IAP12C5A08S2                        \
    || defined TARGET_MODEL_IAP12C5A16                          \
    || defined TARGET_MODEL_IAP12C5A16AD                        \
    || defined TARGET_MODEL_IAP12C5A16CCP                       \
    || defined TARGET_MODEL_IAP12C5A16S2                        \
    || defined TARGET_MODEL_IAP12C5A32                          \
    || defined TARGET_MODEL_IAP12C5A32AD                        \
    || defined TARGET_MODEL_IAP12C5A32CCP                       \
    || defined TARGET_MODEL_IAP12C5A32S2                        \
    || defined TARGET_MODEL_IAP12C5A40                          \
    || defined TARGET_MODEL_IAP12C5A40AD                        \
    || defined TARGET_MODEL_IAP12C5A40CCP                       \
    || defined TARGET_MODEL_IAP12C5A40S2                        \
    || defined TARGET_MODEL_IAP12C5A48                          \
    || defined TARGET_MODEL_IAP12C5A48AD                        \
    || defined TARGET_MODEL_IAP12C5A48CCP                       \
    || defined TARGET_MODEL_IAP12C5A48S2                        \
    || defined TARGET_MODEL_IAP12C5A52                          \
    || defined TARGET_MODEL_IAP12C5A52AD                        \
    || defined TARGET_MODEL_IAP12C5A52CCP                       \
    || defined TARGET_MODEL_IAP12C5A52S2                        \
    || defined TARGET_MODEL_IAP12C5A56                          \
    || defined TARGET_MODEL_IAP12C5A56AD                        \
    || defined TARGET_MODEL_IAP12C5A56CCP                       \
    || defined TARGET_MODEL_IAP12C5A56S2                        \
    || defined TARGET_MODEL_IAP12C5A60                          \
    || defined TARGET_MODEL_IAP12C5A60AD                        \
    || defined TARGET_MODEL_IAP12C5A60CCP                       \
    || defined TARGET_MODEL_IAP12C5A60S2                        \
    || defined TARGET_MODEL_IAP12C5A62                          \
    || defined TARGET_MODEL_IAP12C5A62AD                        \
    || defined TARGET_MODEL_IAP12C5A62CCP                       \
    || defined TARGET_MODEL_IAP12C5A62S2                        \
    || defined TARGET_MODEL_IAP12LE5A08                         \
    || defined TARGET_MODEL_IAP12LE5A08AD                       \
    || defined TARGET_MODEL_IAP12LE5A08CCP                      \
    || defined TARGET_MODEL_IAP12LE5A08S2                       \
    || defined TARGET_MODEL_IAP12LE5A16                         \
    || defined TARGET_MODEL_IAP12LE5A16AD                       \
    || defined TARGET_MODEL_IAP12LE5A16CCP                      \
    || defined TARGET_MODEL_IAP12LE5A16S2                       \
    || defined TARGET_MODEL_IAP12LE5A32                         \
    || defined TARGET_MODEL_IAP12LE5A32AD                       \
    || defined TARGET_MODEL_IAP12LE5A32CCP                      \
    || defined TARGET_MODEL_IAP12LE5A32S2                       \
    || defined TARGET_MODEL_IAP12LE5A40                         \
    || defined TARGET_MODEL_IAP12LE5A40AD                       \
    || defined TARGET_MODEL_IAP12LE5A40CCP                      \
    || defined TARGET_MODEL_IAP12LE5A40S2                       \
    || defined TARGET_MODEL_IAP12LE5A48                         \
    || defined TARGET_MODEL_IAP12LE5A48AD                       \
    || defined TARGET_MODEL_IAP12LE5A48CCP                      \
    || defined TARGET_MODEL_IAP12LE5A48S2                       \
    || defined TARGET_MODEL_IAP12LE5A52                         \
    || defined TARGET_MODEL_IAP12LE5A52AD                       \
    || defined TARGET_MODEL_IAP12LE5A52CCP                      \
    || defined TARGET_MODEL_IAP12LE5A52S2                       \
    || defined TARGET_MODEL_IAP12LE5A56                         \
    || defined TARGET_MODEL_IAP12LE5A56AD                       \
    || defined TARGET_MODEL_IAP12LE5A56CCP                      \
    || defined TARGET_MODEL_IAP12LE5A56S2                       \
    || defined TARGET_MODEL_IAP12LE5A60                         \
    || defined TARGET_MODEL_IAP12LE5A60AD                       \
    || defined TARGET_MODEL_IAP12LE5A60CCP                      \
    || defined TARGET_MODEL_IAP12LE5A60S2                       \
    || defined TARGET_MODEL_IAP12LE5A62                         \
    || defined TARGET_MODEL_IAP12LE5A62AD                       \
    || defined TARGET_MODEL_IAP12LE5A62CCP                      \
    || defined TARGET_MODEL_IAP12LE5A62S2                       \
    || defined TARGET_MODEL_STC12C5A08AD                        \
    || defined TARGET_MODEL_STC12C5A08CCP                       \
    || defined TARGET_MODEL_STC12C5A08S2                        \
    || defined TARGET_MODEL_STC12C5A08X                         \
    || defined TARGET_MODEL_STC12C5A16AD                        \
    || defined TARGET_MODEL_STC12C5A16CCP                       \
    || defined TARGET_MODEL_STC12C5A16S2                        \
    || defined TARGET_MODEL_STC12C5A16X                         \
    || defined TARGET_MODEL_STC12C5A32AD                        \
    || defined TARGET_MODEL_STC12C5A32CCP                       \
    || defined TARGET_MODEL_STC12C5A32S2                        \
    || defined TARGET_MODEL_STC12C5A32X                         \
    || defined TARGET_MODEL_STC12C5A40AD                        \
    || defined TARGET_MODEL_STC12C5A40CCP                       \
    || defined TARGET_MODEL_STC12C5A40S2                        \
    || defined TARGET_MODEL_STC12C5A40X                         \
    || defined TARGET_MODEL_STC12C5A48AD                        \
    || defined TARGET_MODEL_STC12C5A48CCP                       \
    || defined TARGET_MODEL_STC12C5A48S2                        \
    || defined TARGET_MODEL_STC12C5A48X                         \
    || defined TARGET_MODEL_STC12C5A52AD                        \
    || defined TARGET_MODEL_STC12C5A52CCP                       \
    || defined TARGET_MODEL_STC12C5A52S2                        \
    || defined TARGET_MODEL_STC12C5A52X                         \
    || defined TARGET_MODEL_STC12C5A56AD                        \
    || defined TARGET_MODEL_STC12C5A56CCP                       \
    || defined TARGET_MODEL_STC12C5A56S2                        \
    || defined TARGET_MODEL_STC12C5A56X                         \
    || defined TARGET_MODEL_STC12C5A60AD                        \
    || defined TARGET_MODEL_STC12C5A60CCP                       \
    || defined TARGET_MODEL_STC12C5A60S2                        \
    || defined TARGET_MODEL_STC12C5A60X                         \
    || defined TARGET_MODEL_STC12LE5A08AD                       \
    || defined TARGET_MODEL_STC12LE5A08CCP                      \
    || defined TARGET_MODEL_STC12LE5A08S2                       \
    || defined TARGET_MODEL_STC12LE5A08X                        \
    || defined TARGET_MODEL_STC12LE5A16AD                       \
    || defined TARGET_MODEL_STC12LE5A16CCP                      \
    || defined TARGET_MODEL_STC12LE5A16S2                       \
    || defined TARGET_MODEL_STC12LE5A16X                        \
    || defined TARGET_MODEL_STC12LE5A32AD                       \
    || defined TARGET_MODEL_STC12LE5A32CCP                      \
    || defined TARGET_MODEL_STC12LE5A32S2                       \
    || defined TARGET_MODEL_STC12LE5A32X                        \
    || defined TARGET_MODEL_STC12LE5A40AD                       \
    || defined TARGET_MODEL_STC12LE5A40CCP                      \
    || defined TARGET_MODEL_STC12LE5A40S2                       \
    || defined TARGET_MODEL_STC12LE5A40X                        \
    || defined TARGET_MODEL_STC12LE5A48AD                       \
    || defined TARGET_MODEL_STC12LE5A48CCP                      \
    || defined TARGET_MODEL_STC12LE5A48S2                       \
    || defined TARGET_MODEL_STC12LE5A48X                        \
    || defined TARGET_MODEL_STC12LE5A52AD                       \
    || defined TARGET_MODEL_STC12LE5A52CCP                      \
    || defined TARGET_MODEL_STC12LE5A52S2                       \
    || defined TARGET_MODEL_STC12LE5A52X                        \
    || defined TARGET_MODEL_STC12LE5A56AD                       \
    || defined TARGET_MODEL_STC12LE5A56CCP                      \
    || defined TARGET_MODEL_STC12LE5A56S2                       \
    || defined TARGET_MODEL_STC12LE5A56X                        \
    || defined TARGET_MODEL_STC12LE5A60AD                       \
    || defined TARGET_MODEL_STC12LE5A60CCP                      \
    || defined TARGET_MODEL_STC12LE5A60S2                       \
    || defined TARGET_MODEL_STC12LE5A60X
#define TARGET_FAMILY_STC12C5A
#endif

#if defined TARGET_MODEL_IAP10F02                               \
    || defined TARGET_MODEL_IAP10F02XE                          \
    || defined TARGET_MODEL_IAP10F04                            \
    || defined TARGET_MODEL_IAP10F04XE                          \
    || defined TARGET_MODEL_IAP10F06                            \
    || defined TARGET_MODEL_IAP10F06XE                          \
    || defined TARGET_MODEL_IAP10F08                            \
    || defined TARGET_MODEL_IAP10F08XE                          \
    || defined TARGET_MODEL_IAP10F10                            \
    || defined TARGET_MODEL_IAP10F10XE                          \
    || defined TARGET_MODEL_IAP10F12                            \
    || defined TARGET_MODEL_IAP10F12XE                          \
    || defined TARGET_MODEL_IAP10F14                            \
    || defined TARGET_MODEL_IAP10F14X                           \
    || defined TARGET_MODEL_IAP10L02                            \
    || defined TARGET_MODEL_IAP10L02XE                          \
    || defined TARGET_MODEL_IAP10L04                            \
    || defined TARGET_MODEL_IAP10L04XE                          \
    || defined TARGET_MODEL_IAP10L06                            \
    || defined TARGET_MODEL_IAP10L06XE                          \
    || defined TARGET_MODEL_IAP10L08                            \
    || defined TARGET_MODEL_IAP10L08XE                          \
    || defined TARGET_MODEL_IAP10L10                            \
    || defined TARGET_MODEL_IAP10L10XE                          \
    || defined TARGET_MODEL_IAP10L12                            \
    || defined TARGET_MODEL_IAP10L12XE                          \
    || defined TARGET_MODEL_IAP10L14                            \
    || defined TARGET_MODEL_IAP10L14X                           \
    || defined TARGET_MODEL_STC10F02                            \
    || defined TARGET_MODEL_STC10F02X                           \
    || defined TARGET_MODEL_STC10F02XE                          \
    || defined TARGET_MODEL_STC10F04                            \
    || defined TARGET_MODEL_STC10F04X                           \
    || defined TARGET_MODEL_STC10F04XE                          \
    || defined TARGET_MODEL_STC10F06                            \
    || defined TARGET_MODEL_STC10F06X                           \
    || defined TARGET_MODEL_STC10F06XE                          \
    || defined TARGET_MODEL_STC10F08                            \
    || defined TARGET_MODEL_STC10F08X                           \
    || defined TARGET_MODEL_STC10F08XE                          \
    || defined TARGET_MODEL_STC10F10                            \
    || defined TARGET_MODEL_STC10F10X                           \
    || defined TARGET_MODEL_STC10F10XE                          \
    || defined TARGET_MODEL_STC10F12                            \
    || defined TARGET_MODEL_STC10F12X                           \
    || defined TARGET_MODEL_STC10F12XE                          \
    || defined TARGET_MODEL_STC10L02                            \
    || defined TARGET_MODEL_STC10L02X                           \
    || defined TARGET_MODEL_STC10L02XE                          \
    || defined TARGET_MODEL_STC10L04                            \
    || defined TARGET_MODEL_STC10L04X                           \
    || defined TARGET_MODEL_STC10L04XE                          \
    || defined TARGET_MODEL_STC10L06                            \
    || defined TARGET_MODEL_STC10L06X                           \
    || defined TARGET_MODEL_STC10L06XE                          \
    || defined TARGET_MODEL_STC10L08                            \
    || defined TARGET_MODEL_STC10L08X                           \
    || defined TARGET_MODEL_STC10L08XE                          \
    || defined TARGET_MODEL_STC10L10                            \
    || defined TARGET_MODEL_STC10L10X                           \
    || defined TARGET_MODEL_STC10L10XE                          \
    || defined TARGET_MODEL_STC10L12                            \
    || defined TARGET_MODEL_STC10L12X                           \
    || defined TARGET_MODEL_STC10L12XE
#define TARGET_FAMILY_STC10F
#endif

#if defined TARGET_MODEL_IAP11F01                               \
    || defined TARGET_MODEL_IAP11F01E                           \
    || defined TARGET_MODEL_IAP11F02                            \
    || defined TARGET_MODEL_IAP11F02E                           \
    || defined TARGET_MODEL_IAP11F03                            \
    || defined TARGET_MODEL_IAP11F03E                           \
    || defined TARGET_MODEL_IAP11F04                            \
    || defined TARGET_MODEL_IAP11F04E                           \
    || defined TARGET_MODEL_IAP11F05                            \
    || defined TARGET_MODEL_IAP11F05E                           \
    || defined TARGET_MODEL_IAP11F06                            \
    || defined TARGET_MODEL_IAP11F08                            \
    || defined TARGET_MODEL_IAP11F08X                           \
    || defined TARGET_MODEL_IAP11F08XE                          \
    || defined TARGET_MODEL_IAP11F16                            \
    || defined TARGET_MODEL_IAP11F16X                           \
    || defined TARGET_MODEL_IAP11F16XE                          \
    || defined TARGET_MODEL_IAP11F20                            \
    || defined TARGET_MODEL_IAP11F20X                           \
    || defined TARGET_MODEL_IAP11F20XE                          \
    || defined TARGET_MODEL_IAP11F32                            \
    || defined TARGET_MODEL_IAP11F32X                           \
    || defined TARGET_MODEL_IAP11F32XE                          \
    || defined TARGET_MODEL_IAP11F40                            \
    || defined TARGET_MODEL_IAP11F40X                           \
    || defined TARGET_MODEL_IAP11F40XE                          \
    || defined TARGET_MODEL_IAP11F48                            \
    || defined TARGET_MODEL_IAP11F48X                           \
    || defined TARGET_MODEL_IAP11F48XE                          \
    || defined TARGET_MODEL_IAP11F52                            \
    || defined TARGET_MODEL_IAP11F52X                           \
    || defined TARGET_MODEL_IAP11F52XE                          \
    || defined TARGET_MODEL_IAP11F56                            \
    || defined TARGET_MODEL_IAP11F56X                           \
    || defined TARGET_MODEL_IAP11F56XE                          \
    || defined TARGET_MODEL_IAP11F60                            \
    || defined TARGET_MODEL_IAP11F60X                           \
    || defined TARGET_MODEL_IAP11F60XE                          \
    || defined TARGET_MODEL_IAP11F62                            \
    || defined TARGET_MODEL_IAP11F62X                           \
    || defined TARGET_MODEL_IAP11L01                            \
    || defined TARGET_MODEL_IAP11L01E                           \
    || defined TARGET_MODEL_IAP11L02                            \
    || defined TARGET_MODEL_IAP11L02E                           \
    || defined TARGET_MODEL_IAP11L03                            \
    || defined TARGET_MODEL_IAP11L03E                           \
    || defined TARGET_MODEL_IAP11L04                            \
    || defined TARGET_MODEL_IAP11L04E                           \
    || defined TARGET_MODEL_IAP11L05                            \
    || defined TARGET_MODEL_IAP11L05E                           \
    || defined TARGET_MODEL_IAP11L06                            \
    || defined TARGET_MODEL_IAP11L08                            \
    || defined TARGET_MODEL_IAP11L08X                           \
    || defined TARGET_MODEL_IAP11L08XE                          \
    || defined TARGET_MODEL_IAP11L16                            \
    || defined TARGET_MODEL_IAP11L16X                           \
    || defined TARGET_MODEL_IAP11L16XE                          \
    || defined TARGET_MODEL_IAP11L20                            \
    || defined TARGET_MODEL_IAP11L20X                           \
    || defined TARGET_MODEL_IAP11L20XE                          \
    || defined TARGET_MODEL_IAP11L32                            \
    || defined TARGET_MODEL_IAP11L32X                           \
    || defined TARGET_MODEL_IAP11L32XE                          \
    || defined TARGET_MODEL_IAP11L40                            \
    || defined TARGET_MODEL_IAP11L40X                           \
    || defined TARGET_MODEL_IAP11L40XE                          \
    || defined TARGET_MODEL_IAP11L48                            \
    || defined TARGET_MODEL_IAP11L48X                           \
    || defined TARGET_MODEL_IAP11L48XE                          \
    || defined TARGET_MODEL_IAP11L52                            \
    || defined TARGET_MODEL_IAP11L52X                           \
    || defined TARGET_MODEL_IAP11L52XE                          \
    || defined TARGET_MODEL_IAP11L56                            \
    || defined TARGET_MODEL_IAP11L56X                           \
    || defined TARGET_MODEL_IAP11L56XE                          \
    || defined TARGET_MODEL_IAP11L60                            \
    || defined TARGET_MODEL_IAP11L60X                           \
    || defined TARGET_MODEL_IAP11L60XE                          \
    || defined TARGET_MODEL_IAP11L62                            \
    || defined TARGET_MODEL_IAP11L62X                           \
    || defined TARGET_MODEL_STC11F01                            \
    || defined TARGET_MODEL_STC11F01E                           \
    || defined TARGET_MODEL_STC11F02                            \
    || defined TARGET_MODEL_STC11F02E                           \
    || defined TARGET_MODEL_STC11F03                            \
    || defined TARGET_MODEL_STC11F03E                           \
    || defined TARGET_MODEL_STC11F04                            \
    || defined TARGET_MODEL_STC11F04E                           \
    || defined TARGET_MODEL_STC11F05                            \
    || defined TARGET_MODEL_STC11F05E                           \
    || defined TARGET_MODEL_STC11F08                            \
    || defined TARGET_MODEL_STC11F08X                           \
    || defined TARGET_MODEL_STC11F08XE                          \
    || defined TARGET_MODEL_STC11F16                            \
    || defined TARGET_MODEL_STC11F16X                           \
    || defined TARGET_MODEL_STC11F16XE                          \
    || defined TARGET_MODEL_STC11F20                            \
    || defined TARGET_MODEL_STC11F20X                           \
    || defined TARGET_MODEL_STC11F20XE                          \
    || defined TARGET_MODEL_STC11F32                            \
    || defined TARGET_MODEL_STC11F32X                           \
    || defined TARGET_MODEL_STC11F32XE                          \
    || defined TARGET_MODEL_STC11F40                            \
    || defined TARGET_MODEL_STC11F40X                           \
    || defined TARGET_MODEL_STC11F40XE                          \
    || defined TARGET_MODEL_STC11F48                            \
    || defined TARGET_MODEL_STC11F48X                           \
    || defined TARGET_MODEL_STC11F48XE                          \
    || defined TARGET_MODEL_STC11F52                            \
    || defined TARGET_MODEL_STC11F52X                           \
    || defined TARGET_MODEL_STC11F52XE                          \
    || defined TARGET_MODEL_STC11F56                            \
    || defined TARGET_MODEL_STC11F56X                           \
    || defined TARGET_MODEL_STC11F56XE                          \
    || defined TARGET_MODEL_STC11F60                            \
    || defined TARGET_MODEL_STC11F60X                           \
    || defined TARGET_MODEL_STC11F60XE                          \
    || defined TARGET_MODEL_STC11L01                            \
    || defined TARGET_MODEL_STC11L01E                           \
    || defined TARGET_MODEL_STC11L02                            \
    || defined TARGET_MODEL_STC11L02E                           \
    || defined TARGET_MODEL_STC11L03                            \
    || defined TARGET_MODEL_STC11L03E                           \
    || defined TARGET_MODEL_STC11L04                            \
    || defined TARGET_MODEL_STC11L04E                           \
    || defined TARGET_MODEL_STC11L05                            \
    || defined TARGET_MODEL_STC11L05E                           \
    || defined TARGET_MODEL_STC11L08                            \
    || defined TARGET_MODEL_STC11L08X                           \
    || defined TARGET_MODEL_STC11L08XE                          \
    || defined TARGET_MODEL_STC11L16                            \
    || defined TARGET_MODEL_STC11L16X                           \
    || defined TARGET_MODEL_STC11L16XE                          \
    || defined TARGET_MODEL_STC11L20                            \
    || defined TARGET_MODEL_STC11L20X                           \
    || defined TARGET_MODEL_STC11L20XE                          \
    || defined TARGET_MODEL_STC11L32                            \
    || defined TARGET_MODEL_STC11L32X                           \
    || defined TARGET_MODEL_STC11L32XE                          \
    || defined TARGET_MODEL_STC11L40                            \
    || defined TARGET_MODEL_STC11L40X                           \
    || defined TARGET_MODEL_STC11L40XE                          \
    || defined TARGET_MODEL_STC11L48                            \
    || defined TARGET_MODEL_STC11L48X                           \
    || defined TARGET_MODEL_STC11L48XE                          \
    || defined TARGET_MODEL_STC11L52                            \
    || defined TARGET_MODEL_STC11L52X                           \
    || defined TARGET_MODEL_STC11L52XE                          \
    || defined TARGET_MODEL_STC11L56                            \
    || defined TARGET_MODEL_STC11L56X                           \
    || defined TARGET_MODEL_STC11L56XE                          \
    || defined TARGET_MODEL_STC11L60                            \
    || defined TARGET_MODEL_STC11L60X                           \
    || defined TARGET_MODEL_STC11L60XE
#define TARGET_FAMILY_STC11F
#endif

#if defined TARGET_MODEL_STC12C5401                             \
    || defined TARGET_MODEL_STC12C5401AD                        \
    || defined TARGET_MODEL_STC12C5402                          \
    || defined TARGET_MODEL_STC12C5402AD                        \
    || defined TARGET_MODEL_STC12C5404                          \
    || defined TARGET_MODEL_STC12C5404AD                        \
    || defined TARGET_MODEL_STC12C5406                          \
    || defined TARGET_MODEL_STC12C5406AD                        \
    || defined TARGET_MODEL_STC12C5408                          \
    || defined TARGET_MODEL_STC12C5408AD                        \
    || defined TARGET_MODEL_STC12C5410                          \
    || defined TARGET_MODEL_STC12C5410AD                        \
    || defined TARGET_MODEL_STC12C5412                          \
    || defined TARGET_MODEL_STC12C5412AD                        \
    || defined TARGET_MODEL_STC12C5416                          \
    || defined TARGET_MODEL_STC12C5416AD                        \
    || defined TARGET_MODEL_STC12C5420                          \
    || defined TARGET_MODEL_STC12C5420AD                        \
    || defined TARGET_MODEL_STC12C5424                          \
    || defined TARGET_MODEL_STC12C5424AD                        \
    || defined TARGET_MODEL_STC12C5428                          \
    || defined TARGET_MODEL_STC12C5428AD                        \
    || defined TARGET_MODEL_STC12LE5401                         \
    || defined TARGET_MODEL_STC12LE5401AD                       \
    || defined TARGET_MODEL_STC12LE5402                         \
    || defined TARGET_MODEL_STC12LE5402AD                       \
    || defined TARGET_MODEL_STC12LE5404                         \
    || defined TARGET_MODEL_STC12LE5404AD                       \
    || defined TARGET_MODEL_STC12LE5406                         \
    || defined TARGET_MODEL_STC12LE5406AD                       \
    || defined TARGET_MODEL_STC12LE5408                         \
    || defined TARGET_MODEL_STC12LE5408AD                       \
    || defined TARGET_MODEL_STC12LE5410                         \
    || defined TARGET_MODEL_STC12LE5410AD                       \
    || defined TARGET_MODEL_STC12LE5412                         \
    || defined TARGET_MODEL_STC12LE5412AD                       \
    || defined TARGET_MODEL_STC12LE5416                         \
    || defined TARGET_MODEL_STC12LE5416AD                       \
    || defined TARGET_MODEL_STC12LE5420                         \
    || defined TARGET_MODEL_STC12LE5420AD                       \
    || defined TARGET_MODEL_STC12LE5424                         \
    || defined TARGET_MODEL_STC12LE5424AD                       \
    || defined TARGET_MODEL_STC12LE5428                         \
    || defined TARGET_MODEL_STC12LE5428AD
#define TARGET_FAMILY_STC12C54
#endif

#if defined TARGET_MODEL_STC12C5601                             \
    || defined TARGET_MODEL_STC12C5601AD                        \
    || defined TARGET_MODEL_STC12C5602                          \
    || defined TARGET_MODEL_STC12C5602AD                        \
    || defined TARGET_MODEL_STC12C5603                          \
    || defined TARGET_MODEL_STC12C5603AD                        \
    || defined TARGET_MODEL_STC12C5604                          \
    || defined TARGET_MODEL_STC12C5604AD                        \
    || defined TARGET_MODEL_STC12C5605                          \
    || defined TARGET_MODEL_STC12C5605AD                        \
    || defined TARGET_MODEL_STC12C5606                          \
    || defined TARGET_MODEL_STC12C5606AD                        \
    || defined TARGET_MODEL_STC12C5608                          \
    || defined TARGET_MODEL_STC12C5608AD                        \
    || defined TARGET_MODEL_STC12C5612                          \
    || defined TARGET_MODEL_STC12C5612AD                        \
    || defined TARGET_MODEL_STC12C5616                          \
    || defined TARGET_MODEL_STC12C5616AD                        \
    || defined TARGET_MODEL_STC12C5620                          \
    || defined TARGET_MODEL_STC12C5620AD                        \
    || defined TARGET_MODEL_STC12C5624                          \
    || defined TARGET_MODEL_STC12C5624AD                        \
    || defined TARGET_MODEL_STC12C5628                          \
    || defined TARGET_MODEL_STC12C5628AD                        \
    || defined TARGET_MODEL_STC12C5630                          \
    || defined TARGET_MODEL_STC12C5630AD                        \
    || defined TARGET_MODEL_STC12LE5601                         \
    || defined TARGET_MODEL_STC12LE5601AD                       \
    || defined TARGET_MODEL_STC12LE5602                         \
    || defined TARGET_MODEL_STC12LE5602AD                       \
    || defined TARGET_MODEL_STC12LE5603                         \
    || defined TARGET_MODEL_STC12LE5603AD                       \
    || defined TARGET_MODEL_STC12LE5604                         \
    || defined TARGET_MODEL_STC12LE5604AD                       \
    || defined TARGET_MODEL_STC12LE5605                         \
    || defined TARGET_MODEL_STC12LE5605AD                       \
    || defined TARGET_MODEL_STC12LE5606                         \
    || defined TARGET_MODEL_STC12LE5606AD                       \
    || defined TARGET_MODEL_STC12LE5608                         \
    || defined TARGET_MODEL_STC12LE5608AD                       \
    || defined TARGET_MODEL_STC12LE5612                         \
    || defined TARGET_MODEL_STC12LE5612AD                       \
    || defined TARGET_MODEL_STC12LE5616                         \
    || defined TARGET_MODEL_STC12LE5616AD                       \
    || defined TARGET_MODEL_STC12LE5620                         \
    || defined TARGET_MODEL_STC12LE5620AD                       \
    || defined TARGET_MODEL_STC12LE5624                         \
    || defined TARGET_MODEL_STC12LE5624AD                       \
    || defined TARGET_MODEL_STC12LE5628                         \
    || defined TARGET_MODEL_STC12LE5628AD                       \
    || defined TARGET_MODEL_STC12LE5630                         \
    || defined TARGET_MODEL_STC12LE5630AD
#define TARGET_FAMILY_STC12C56
#endif

#if defined TARGET_MODEL_STC12C1052                             \
    || defined TARGET_MODEL_STC12C1052AD                        \
    || defined TARGET_MODEL_STC12C2052                          \
    || defined TARGET_MODEL_STC12C2052AD                        \
    || defined TARGET_MODEL_STC12C3052                          \
    || defined TARGET_MODEL_STC12C3052AD                        \
    || defined TARGET_MODEL_STC12C4052                          \
    || defined TARGET_MODEL_STC12C4052AD                        \
    || defined TARGET_MODEL_STC12C5052                          \
    || defined TARGET_MODEL_STC12C5052AD                        \
    || defined TARGET_MODEL_STC12LE1052                         \
    || defined TARGET_MODEL_STC12LE1052AD                       \
    || defined TARGET_MODEL_STC12LE2052                         \
    || defined TARGET_MODEL_STC12LE2052AD                       \
    || defined TARGET_MODEL_STC12LE3052                         \
    || defined TARGET_MODEL_STC12LE3052AD                       \
    || defined TARGET_MODEL_STC12LE4052                         \
    || defined TARGET_MODEL_STC12LE4052AD                       \
    || defined TARGET_MODEL_STC12LE5052                         \
    || defined TARGET_MODEL_STC12LE5052AD
#define TARGET_FAMILY_STC12Cx052
#endif

#if defined TARGET_MODEL_STC90C510AD                            \
    || defined TARGET_MODEL_STC90C512AD                         \
    || defined TARGET_MODEL_STC90C513AD                         \
    || defined TARGET_MODEL_STC90C514AD                         \
    || defined TARGET_MODEL_STC90C516AD                         \
    || defined TARGET_MODEL_STC90C51AD                          \
    || defined TARGET_MODEL_STC90C52AD                          \
    || defined TARGET_MODEL_STC90C54AD                          \
    || defined TARGET_MODEL_STC90C55AD                          \
    || defined TARGET_MODEL_STC90C58AD                          \
    || defined TARGET_MODEL_STC90LE510AD                        \
    || defined TARGET_MODEL_STC90LE512AD                        \
    || defined TARGET_MODEL_STC90LE513AD                        \
    || defined TARGET_MODEL_STC90LE514AD                        \
    || defined TARGET_MODEL_STC90LE516AD                        \
    || defined TARGET_MODEL_STC90LE51AD                         \
    || defined TARGET_MODEL_STC90LE52AD                         \
    || defined TARGET_MODEL_STC90LE54AD                         \
    || defined TARGET_MODEL_STC90LE55AD                         \
    || defined TARGET_MODEL_STC90LE58AD
#define TARGET_FAMILY_STC90CxAD
#endif

#if defined TARGET_MODEL_STC90C06RC                             \
    || defined TARGET_MODEL_STC90C07RC                          \
    || defined TARGET_MODEL_STC90C10RC                          \
    || defined TARGET_MODEL_STC90C12RC                          \
    || defined TARGET_MODEL_STC90C510RD_                        \
    || defined TARGET_MODEL_STC90C512RD_                        \
    || defined TARGET_MODEL_STC90C513RD_                        \
    || defined TARGET_MODEL_STC90C514RD_                        \
    || defined TARGET_MODEL_STC90C516RD_                        \
    || defined TARGET_MODEL_STC90C51RC                          \
    || defined TARGET_MODEL_STC90C51RD_                         \
    || defined TARGET_MODEL_STC90C52RC                          \
    || defined TARGET_MODEL_STC90C52RD_                         \
    || defined TARGET_MODEL_STC90C53RC                          \
    || defined TARGET_MODEL_STC90C54RD_                         \
    || defined TARGET_MODEL_STC90C55RD_                         \
    || defined TARGET_MODEL_STC90C58RD_                         \
    || defined TARGET_MODEL_STC90LE06RC                         \
    || defined TARGET_MODEL_STC90LE07RC                         \
    || defined TARGET_MODEL_STC90LE10RC                         \
    || defined TARGET_MODEL_STC90LE12RC                         \
    || defined TARGET_MODEL_STC90LE510RD_                       \
    || defined TARGET_MODEL_STC90LE512RD_                       \
    || defined TARGET_MODEL_STC90LE513RD_                       \
    || defined TARGET_MODEL_STC90LE514RD_                       \
    || defined TARGET_MODEL_STC90LE516RD_                       \
    || defined TARGET_MODEL_STC90LE51RC                         \
    || defined TARGET_MODEL_STC90LE51RD_                        \
    || defined TARGET_MODEL_STC90LE52RC                         \
    || defined TARGET_MODEL_STC90LE52RD_                        \
    || defined TARGET_MODEL_STC90LE53RC                         \
    || defined TARGET_MODEL_STC90LE54RD_                        \
    || defined TARGET_MODEL_STC90LE55RD_                        \
    || defined TARGET_MODEL_STC90LE58RD_
#define TARGET_FAMILY_STC90CxR
#endif

#if defined TARGET_MODEL_STC89C51                               \
    || defined TARGET_MODEL_STC89C510                           \
    || defined TARGET_MODEL_STC89C510RD_                        \
    || defined TARGET_MODEL_STC89C512                           \
    || defined TARGET_MODEL_STC89C512RD_                        \
    || defined TARGET_MODEL_STC89C513RD_                        \
    || defined TARGET_MODEL_STC89C514                           \
    || defined TARGET_MODEL_STC89C514RD_                        \
    || defined TARGET_MODEL_STC89C516                           \
    || defined TARGET_MODEL_STC89C516RD                         \
    || defined TARGET_MODEL_STC89C516RD_                        \
    || defined TARGET_MODEL_STC89C51RC                          \
    || defined TARGET_MODEL_STC89C51RD_                         \
    || defined TARGET_MODEL_STC89C52                            \
    || defined TARGET_MODEL_STC89C52RC                          \
    || defined TARGET_MODEL_STC89C52RD_                         \
    || defined TARGET_MODEL_STC89C53                            \
    || defined TARGET_MODEL_STC89C53RC                          \
    || defined TARGET_MODEL_STC89C54                            \
    || defined TARGET_MODEL_STC89C54RD_                         \
    || defined TARGET_MODEL_STC89C55RD_                         \
    || defined TARGET_MODEL_STC89C58                            \
    || defined TARGET_MODEL_STC89C58RD_                         \
    || defined TARGET_MODEL_STC89LE51                           \
    || defined TARGET_MODEL_STC89LE510                          \
    || defined TARGET_MODEL_STC89LE512                          \
    || defined TARGET_MODEL_STC89LE514                          \
    || defined TARGET_MODEL_STC89LE516                          \
    || defined TARGET_MODEL_STC89LE516RD_                       \
    || defined TARGET_MODEL_STC89LE51RC                         \
    || defined TARGET_MODEL_STC89LE52                           \
    || defined TARGET_MODEL_STC89LE52RC                         \
    || defined TARGET_MODEL_STC89LE53                           \
    || defined TARGET_MODEL_STC89LE53RC                         \
    || defined TARGET_MODEL_STC89LE54                           \
    || defined TARGET_MODEL_STC89LE54RD_                        \
    || defined TARGET_MODEL_STC89LE58                           \
    || defined TARGET_MODEL_STC89LE58RD_
#define TARGET_FAMILY_STC89C
#endif


#endif /* __MODELDB_H */
