#ifndef __MODELDB_H
#define __MODELDB_H


#if defined TARGET_MODEL_STC12C5201                             \
    || defined TARGET_MODEL_STC12C5201AD                        \
    || defined TARGET_MODEL_STC12C5201PWM                       \
    || defined TARGET_MODEL_STC12C5202                          \
    || defined TARGET_MODEL_STC12C5202AD                        \
    || defined TARGET_MODEL_STC12C5202PWM                       \
    || defined TARGET_MODEL_STC12C5203                          \
    || defined TARGET_MODEL_STC12C5203AD                        \
    || defined TARGET_MODEL_STC12C5203PWM                       \
    || defined TARGET_MODEL_STC12C5204                          \
    || defined TARGET_MODEL_STC12C5204AD                        \
    || defined TARGET_MODEL_STC12C5204PWM                       \
    || defined TARGET_MODEL_STC12C5205                          \
    || defined TARGET_MODEL_STC12C5205AD                        \
    || defined TARGET_MODEL_STC12C5205PWM                       \
    || defined TARGET_MODEL_STC12C5206                          \
    || defined TARGET_MODEL_STC12C5206AD                        \
    || defined TARGET_MODEL_STC12C5206PWM                       \
    || defined TARGET_MODEL_STC12C52xx                          \
    || defined TARGET_MODEL_STC12LE5201                         \
    || defined TARGET_MODEL_STC12LE5201AD                       \
    || defined TARGET_MODEL_STC12LE5201PWM                      \
    || defined TARGET_MODEL_STC12LE5202                         \
    || defined TARGET_MODEL_STC12LE5202AD                       \
    || defined TARGET_MODEL_STC12LE5202PWM                      \
    || defined TARGET_MODEL_STC12LE5203                         \
    || defined TARGET_MODEL_STC12LE5203AD                       \
    || defined TARGET_MODEL_STC12LE5203PWM                      \
    || defined TARGET_MODEL_STC12LE5204                         \
    || defined TARGET_MODEL_STC12LE5204AD                       \
    || defined TARGET_MODEL_STC12LE5204PWM                      \
    || defined TARGET_MODEL_STC12LE5205                         \
    || defined TARGET_MODEL_STC12LE5205AD                       \
    || defined TARGET_MODEL_STC12LE5205PWM                      \
    || defined TARGET_MODEL_STC12LE5206                         \
    || defined TARGET_MODEL_STC12LE5206AD                       \
    || defined TARGET_MODEL_STC12LE5206PWM
#define TARGET_FAMILY_STC12C52
#endif

#if defined TARGET_MODEL_IAP12C5A08                             \
    || defined TARGET_MODEL_IAP12C5A08AD                        \
    || defined TARGET_MODEL_IAP12C5A08CCP                       \
    || defined TARGET_MODEL_IAP12C5A08S2                        \
    || defined TARGET_MODEL_IAP12C5A16                          \
    || defined TARGET_MODEL_IAP12C5A16AD                        \
    || defined TARGET_MODEL_IAP12C5A16CCP                       \
    || defined TARGET_MODEL_IAP12C5A16S2                        \
    || defined TARGET_MODEL_IAP12C5A32                          \
    || defined TARGET_MODEL_IAP12C5A32AD                        \
    || defined TARGET_MODEL_IAP12C5A32CCP                       \
    || defined TARGET_MODEL_IAP12C5A32S2                        \
    || defined TARGET_MODEL_IAP12C5A40                          \
    || defined TARGET_MODEL_IAP12C5A40AD                        \
    || defined TARGET_MODEL_IAP12C5A40CCP                       \
    || defined TARGET_MODEL_IAP12C5A40S2                        \
    || defined TARGET_MODEL_IAP12C5A48                          \
    || defined TARGET_MODEL_IAP12C5A48AD                        \
    || defined TARGET_MODEL_IAP12C5A48CCP                       \
    || defined TARGET_MODEL_IAP12C5A48S2                        \
    || defined TARGET_MODEL_IAP12C5A52                          \
    || defined TARGET_MODEL_IAP12C5A52AD                        \
    || defined TARGET_MODEL_IAP12C5A52CCP                       \
    || defined TARGET_MODEL_IAP12C5A52S2                        \
    || defined TARGET_MODEL_IAP12C5A56                          \
    || defined TARGET_MODEL_IAP12C5A56AD                        \
    || defined TARGET_MODEL_IAP12C5A56CCP                       \
    || defined TARGET_MODEL_IAP12C5A56S2                        \
    || defined TARGET_MODEL_IAP12C5A60                          \
    || defined TARGET_MODEL_IAP12C5A60AD                        \
    || defined TARGET_MODEL_IAP12C5A60CCP                       \
    || defined TARGET_MODEL_IAP12C5A60S2                        \
    || defined TARGET_MODEL_IAP12C5A62                          \
    || defined TARGET_MODEL_IAP12C5A62AD                        \
    || defined TARGET_MODEL_IAP12C5A62CCP                       \
    || defined TARGET_MODEL_IAP12C5A62S2                        \
    || defined TARGET_MODEL_IAP12LE5A08                         \
    || defined TARGET_MODEL_IAP12LE5A08AD                       \
    || defined TARGET_MODEL_IAP12LE5A08CCP                      \
    || defined TARGET_MODEL_IAP12LE5A08S2                       \
    || defined TARGET_MODEL_IAP12LE5A16                         \
    || defined TARGET_MODEL_IAP12LE5A16AD                       \
    || defined TARGET_MODEL_IAP12LE5A16CCP                      \
    || defined TARGET_MODEL_IAP12LE5A16S2                       \
    || defined TARGET_MODEL_IAP12LE5A32                         \
    || defined TARGET_MODEL_IAP12LE5A32AD                       \
    || defined TARGET_MODEL_IAP12LE5A32CCP                      \
    || defined TARGET_MODEL_IAP12LE5A32S2                       \
    || defined TARGET_MODEL_IAP12LE5A40                         \
    || defined TARGET_MODEL_IAP12LE5A40AD                       \
    || defined TARGET_MODEL_IAP12LE5A40CCP                      \
    || defined TARGET_MODEL_IAP12LE5A40S2                       \
    || defined TARGET_MODEL_IAP12LE5A48                         \
    || defined TARGET_MODEL_IAP12LE5A48AD                       \
    || defined TARGET_MODEL_IAP12LE5A48CCP                      \
    || defined TARGET_MODEL_IAP12LE5A48S2                       \
    || defined TARGET_MODEL_IAP12LE5A52                         \
    || defined TARGET_MODEL_IAP12LE5A52AD                       \
    || defined TARGET_MODEL_IAP12LE5A52CCP                      \
    || defined TARGET_MODEL_IAP12LE5A52S2                       \
    || defined TARGET_MODEL_IAP12LE5A56                         \
    || defined TARGET_MODEL_IAP12LE5A56AD                       \
    || defined TARGET_MODEL_IAP12LE5A56CCP                      \
    || defined TARGET_MODEL_IAP12LE5A56S2                       \
    || defined TARGET_MODEL_IAP12LE5A60                         \
    || defined TARGET_MODEL_IAP12LE5A60AD                       \
    || defined TARGET_MODEL_IAP12LE5A60CCP                      \
    || defined TARGET_MODEL_IAP12LE5A60S2                       \
    || defined TARGET_MODEL_IAP12LE5A62                         \
    || defined TARGET_MODEL_IAP12LE5A62AD                       \
    || defined TARGET_MODEL_IAP12LE5A62CCP                      \
    || defined TARGET_MODEL_IAP12LE5A62S2                       \
    || defined TARGET_MODEL_STC12C5A08AD                        \
    || defined TARGET_MODEL_STC12C5A08CCP                       \
    || defined TARGET_MODEL_STC12C5A08S2                        \
    || defined TARGET_MODEL_STC12C5A08X                         \
    || defined TARGET_MODEL_STC12C5A16AD                        \
    || defined TARGET_MODEL_STC12C5A16CCP                       \
    || defined TARGET_MODEL_STC12C5A16S2                        \
    || defined TARGET_MODEL_STC12C5A16X                         \
    || defined TARGET_MODEL_STC12C5A32AD                        \
    || defined TARGET_MODEL_STC12C5A32CCP                       \
    || defined TARGET_MODEL_STC12C5A32S2                        \
    || defined TARGET_MODEL_STC12C5A32X                         \
    || defined TARGET_MODEL_STC12C5A40AD                        \
    || defined TARGET_MODEL_STC12C5A40CCP                       \
    || defined TARGET_MODEL_STC12C5A40S2                        \
    || defined TARGET_MODEL_STC12C5A40X                         \
    || defined TARGET_MODEL_STC12C5A48AD                        \
    || defined TARGET_MODEL_STC12C5A48CCP                       \
    || defined TARGET_MODEL_STC12C5A48S2                        \
    || defined TARGET_MODEL_STC12C5A48X                         \
    || defined TARGET_MODEL_STC12C5A52AD                        \
    || defined TARGET_MODEL_STC12C5A52CCP                       \
    || defined TARGET_MODEL_STC12C5A52S2                        \
    || defined TARGET_MODEL_STC12C5A52X                         \
    || defined TARGET_MODEL_STC12C5A56AD                        \
    || defined TARGET_MODEL_STC12C5A56CCP                       \
    || defined TARGET_MODEL_STC12C5A56S2                        \
    || defined TARGET_MODEL_STC12C5A56X                         \
    || defined TARGET_MODEL_STC12C5A60AD                        \
    || defined TARGET_MODEL_STC12C5A60CCP                       \
    || defined TARGET_MODEL_STC12C5A60S2                        \
    || defined TARGET_MODEL_STC12C5A60X                         \
    || defined TARGET_MODEL_STC12C5Axx                          \
    || defined TARGET_MODEL_STC12LE5A08AD                       \
    || defined TARGET_MODEL_STC12LE5A08CCP                      \
    || defined TARGET_MODEL_STC12LE5A08S2                       \
    || defined TARGET_MODEL_STC12LE5A08X                        \
    || defined TARGET_MODEL_STC12LE5A16AD                       \
    || defined TARGET_MODEL_STC12LE5A16CCP                      \
    || defined TARGET_MODEL_STC12LE5A16S2                       \
    || defined TARGET_MODEL_STC12LE5A16X                        \
    || defined TARGET_MODEL_STC12LE5A32AD                       \
    || defined TARGET_MODEL_STC12LE5A32CCP                      \
    || defined TARGET_MODEL_STC12LE5A32S2                       \
    || defined TARGET_MODEL_STC12LE5A32X                        \
    || defined TARGET_MODEL_STC12LE5A40AD                       \
    || defined TARGET_MODEL_STC12LE5A40CCP                      \
    || defined TARGET_MODEL_STC12LE5A40S2                       \
    || defined TARGET_MODEL_STC12LE5A40X                        \
    || defined TARGET_MODEL_STC12LE5A48AD                       \
    || defined TARGET_MODEL_STC12LE5A48CCP                      \
    || defined TARGET_MODEL_STC12LE5A48S2                       \
    || defined TARGET_MODEL_STC12LE5A48X                        \
    || defined TARGET_MODEL_STC12LE5A52AD                       \
    || defined TARGET_MODEL_STC12LE5A52CCP                      \
    || defined TARGET_MODEL_STC12LE5A52S2                       \
    || defined TARGET_MODEL_STC12LE5A52X                        \
    || defined TARGET_MODEL_STC12LE5A56AD                       \
    || defined TARGET_MODEL_STC12LE5A56CCP                      \
    || defined TARGET_MODEL_STC12LE5A56S2                       \
    || defined TARGET_MODEL_STC12LE5A56X                        \
    || defined TARGET_MODEL_STC12LE5A60AD                       \
    || defined TARGET_MODEL_STC12LE5A60CCP                      \
    || defined TARGET_MODEL_STC12LE5A60S2                       \
    || defined TARGET_MODEL_STC12LE5A60X
#define TARGET_FAMILY_STC12C5A
#endif

#if defined TARGET_MODEL_IAP10F02                               \
    || defined TARGET_MODEL_IAP10F02XE                          \
    || defined TARGET_MODEL_IAP10F04                            \
    || defined TARGET_MODEL_IAP10F04XE                          \
    || defined TARGET_MODEL_IAP10F06                            \
    || defined TARGET_MODEL_IAP10F06XE                          \
    || defined TARGET_MODEL_IAP10F08                            \
    || defined TARGET_MODEL_IAP10F08XE                          \
    || defined TARGET_MODEL_IAP10F10                            \
    || defined TARGET_MODEL_IAP10F10XE                          \
    || defined TARGET_MODEL_IAP10F12                            \
    || defined TARGET_MODEL_IAP10F12XE                          \
    || defined TARGET_MODEL_IAP10F14                            \
    || defined TARGET_MODEL_IAP10F14X                           \
    || defined TARGET_MODEL_IAP10L02                            \
    || defined TARGET_MODEL_IAP10L02XE                          \
    || defined TARGET_MODEL_IAP10L04                            \
    || defined TARGET_MODEL_IAP10L04XE                          \
    || defined TARGET_MODEL_IAP10L06                            \
    || defined TARGET_MODEL_IAP10L06XE                          \
    || defined TARGET_MODEL_IAP10L08                            \
    || defined TARGET_MODEL_IAP10L08XE                          \
    || defined TARGET_MODEL_IAP10L10                            \
    || defined TARGET_MODEL_IAP10L10XE                          \
    || defined TARGET_MODEL_IAP10L12                            \
    || defined TARGET_MODEL_IAP10L12XE                          \
    || defined TARGET_MODEL_IAP10L14                            \
    || defined TARGET_MODEL_IAP10L14X                           \
    || defined TARGET_MODEL_STC10F02                            \
    || defined TARGET_MODEL_STC10F02X                           \
    || defined TARGET_MODEL_STC10F02XE                          \
    || defined TARGET_MODEL_STC10F04                            \
    || defined TARGET_MODEL_STC10F04X                           \
    || defined TARGET_MODEL_STC10F04XE                          \
    || defined TARGET_MODEL_STC10F06                            \
    || defined TARGET_MODEL_STC10F06X                           \
    || defined TARGET_MODEL_STC10F06XE                          \
    || defined TARGET_MODEL_STC10F08                            \
    || defined TARGET_MODEL_STC10F08X                           \
    || defined TARGET_MODEL_STC10F08XE                          \
    || defined TARGET_MODEL_STC10F10                            \
    || defined TARGET_MODEL_STC10F10X                           \
    || defined TARGET_MODEL_STC10F10XE                          \
    || defined TARGET_MODEL_STC10F12                            \
    || defined TARGET_MODEL_STC10F12X                           \
    || defined TARGET_MODEL_STC10F12XE                          \
    || defined TARGET_MODEL_STC10Fxx                            \
    || defined TARGET_MODEL_STC10L02                            \
    || defined TARGET_MODEL_STC10L02X                           \
    || defined TARGET_MODEL_STC10L02XE                          \
    || defined TARGET_MODEL_STC10L04                            \
    || defined TARGET_MODEL_STC10L04X                           \
    || defined TARGET_MODEL_STC10L04XE                          \
    || defined TARGET_MODEL_STC10L06                            \
    || defined TARGET_MODEL_STC10L06X                           \
    || defined TARGET_MODEL_STC10L06XE                          \
    || defined TARGET_MODEL_STC10L08                            \
    || defined TARGET_MODEL_STC10L08X                           \
    || defined TARGET_MODEL_STC10L08XE                          \
    || defined TARGET_MODEL_STC10L10                            \
    || defined TARGET_MODEL_STC10L10X                           \
    || defined TARGET_MODEL_STC10L10XE                          \
    || defined TARGET_MODEL_STC10L12                            \
    || defined TARGET_MODEL_STC10L12X                           \
    || defined TARGET_MODEL_STC10L12XE                          \
    || defined TARGET_MODEL_STC10Lxx
#define TARGET_FAMILY_STC10F
#endif

#if defined TARGET_MODEL_IAP11F01                               \
    || defined TARGET_MODEL_IAP11F01E                           \
    || defined TARGET_MODEL_IAP11F02                            \
    || defined TARGET_MODEL_IAP11F02E                           \
    || defined TARGET_MODEL_IAP11F03                            \
    || defined TARGET_MODEL_IAP11F03E                           \
    || defined TARGET_MODEL_IAP11F04                            \
    || defined TARGET_MODEL_IAP11F04E                           \
    || defined TARGET_MODEL_IAP11F05                            \
    || defined TARGET_MODEL_IAP11F05E                           \
    || defined TARGET_MODEL_IAP11F06                            \
    || defined TARGET_MODEL_IAP11F08                            \
    || defined TARGET_MODEL_IAP11F08X                           \
    || defined TARGET_MODEL_IAP11F08XE                          \
    || defined TARGET_MODEL_IAP11F16                            \
    || defined TARGET_MODEL_IAP11F16X                           \
    || defined TARGET_MODEL_IAP11F16XE                          \
    || defined TARGET_MODEL_IAP11F20                            \
    || defined TARGET_MODEL_IAP11F20X                           \
    || defined TARGET_MODEL_IAP11F20XE                          \
    || defined TARGET_MODEL_IAP11F32                            \
    || defined TARGET_MODEL_IAP11F32X                           \
    || defined TARGET_MODEL_IAP11F32XE                          \
    || defined TARGET_MODEL_IAP11F40                            \
    || defined TARGET_MODEL_IAP11F40X                           \
    || defined TARGET_MODEL_IAP11F40XE                          \
    || defined TARGET_MODEL_IAP11F48                            \
    || defined TARGET_MODEL_IAP11F48X                           \
    || defined TARGET_MODEL_IAP11F48XE                          \
    || defined TARGET_MODEL_IAP11F52                            \
    || defined TARGET_MODEL_IAP11F52X                           \
    || defined TARGET_MODEL_IAP11F52XE                          \
    || defined TARGET_MODEL_IAP11F56                            \
    || defined TARGET_MODEL_IAP11F56X                           \
    || defined TARGET_MODEL_IAP11F56XE                          \
    || defined TARGET_MODEL_IAP11F60                            \
    || defined TARGET_MODEL_IAP11F60X                           \
    || defined TARGET_MODEL_IAP11F60XE                          \
    || defined TARGET_MODEL_IAP11F62                            \
    || defined TARGET_MODEL_IAP11F62X                           \
    || defined TARGET_MODEL_IAP11L01                            \
    || defined TARGET_MODEL_IAP11L01E                           \
    || defined TARGET_MODEL_IAP11L02                            \
    || defined TARGET_MODEL_IAP11L02E                           \
    || defined TARGET_MODEL_IAP11L03                            \
    || defined TARGET_MODEL_IAP11L03E                           \
    || defined TARGET_MODEL_IAP11L04                            \
    || defined TARGET_MODEL_IAP11L04E                           \
    || defined TARGET_MODEL_IAP11L05                            \
    || defined TARGET_MODEL_IAP11L05E                           \
    || defined TARGET_MODEL_IAP11L06                            \
    || defined TARGET_MODEL_IAP11L08                            \
    || defined TARGET_MODEL_IAP11L08X                           \
    || defined TARGET_MODEL_IAP11L08XE                          \
    || defined TARGET_MODEL_IAP11L16                            \
    || defined TARGET_MODEL_IAP11L16X                           \
    || defined TARGET_MODEL_IAP11L16XE                          \
    || defined TARGET_MODEL_IAP11L20                            \
    || defined TARGET_MODEL_IAP11L20X                           \
    || defined TARGET_MODEL_IAP11L20XE                          \
    || defined TARGET_MODEL_IAP11L32                            \
    || defined TARGET_MODEL_IAP11L32X                           \
    || defined TARGET_MODEL_IAP11L32XE                          \
    || defined TARGET_MODEL_IAP11L40                            \
    || defined TARGET_MODEL_IAP11L40X                           \
    || defined TARGET_MODEL_IAP11L40XE                          \
    || defined TARGET_MODEL_IAP11L48                            \
    || defined TARGET_MODEL_IAP11L48X                           \
    || defined TARGET_MODEL_IAP11L48XE                          \
    || defined TARGET_MODEL_IAP11L52                            \
    || defined TARGET_MODEL_IAP11L52X                           \
    || defined TARGET_MODEL_IAP11L52XE                          \
    || defined TARGET_MODEL_IAP11L56                            \
    || defined TARGET_MODEL_IAP11L56X                           \
    || defined TARGET_MODEL_IAP11L56XE                          \
    || defined TARGET_MODEL_IAP11L60                            \
    || defined TARGET_MODEL_IAP11L60X                           \
    || defined TARGET_MODEL_IAP11L60XE                          \
    || defined TARGET_MODEL_IAP11L62                            \
    || defined TARGET_MODEL_IAP11L62X                           \
    || defined TARGET_MODEL_STC11F01                            \
    || defined TARGET_MODEL_STC11F01E                           \
    || defined TARGET_MODEL_STC11F02                            \
    || defined TARGET_MODEL_STC11F02E                           \
    || defined TARGET_MODEL_STC11F03                            \
    || defined TARGET_MODEL_STC11F03E                           \
    || defined TARGET_MODEL_STC11F04                            \
    || defined TARGET_MODEL_STC11F04E                           \
    || defined TARGET_MODEL_STC11F05                            \
    || defined TARGET_MODEL_STC11F05E                           \
    || defined TARGET_MODEL_STC11F08                            \
    || defined TARGET_MODEL_STC11F08X                           \
    || defined TARGET_MODEL_STC11F08XE                          \
    || defined TARGET_MODEL_STC11F16                            \
    || defined TARGET_MODEL_STC11F16X                           \
    || defined TARGET_MODEL_STC11F16XE                          \
    || defined TARGET_MODEL_STC11F20                            \
    || defined TARGET_MODEL_STC11F20X                           \
    || defined TARGET_MODEL_STC11F20XE                          \
    || defined TARGET_MODEL_STC11F32                            \
    || defined TARGET_MODEL_STC11F32X                           \
    || defined TARGET_MODEL_STC11F32XE                          \
    || defined TARGET_MODEL_STC11F40                            \
    || defined TARGET_MODEL_STC11F40X                           \
    || defined TARGET_MODEL_STC11F40XE                          \
    || defined TARGET_MODEL_STC11F48                            \
    || defined TARGET_MODEL_STC11F48X                           \
    || defined TARGET_MODEL_STC11F48XE                          \
    || defined TARGET_MODEL_STC11F52                            \
    || defined TARGET_MODEL_STC11F52X                           \
    || defined TARGET_MODEL_STC11F52XE                          \
    || defined TARGET_MODEL_STC11F56                            \
    || defined TARGET_MODEL_STC11F56X                           \
    || defined TARGET_MODEL_STC11F56XE                          \
    || defined TARGET_MODEL_STC11F60                            \
    || defined TARGET_MODEL_STC11F60X                           \
    || defined TARGET_MODEL_STC11F60XE                          \
    || defined TARGET_MODEL_STC11Fxx                            \
    || defined TARGET_MODEL_STC11L01                            \
    || defined TARGET_MODEL_STC11L01E                           \
    || defined TARGET_MODEL_STC11L02                            \
    || defined TARGET_MODEL_STC11L02E                           \
    || defined TARGET_MODEL_STC11L03                            \
    || defined TARGET_MODEL_STC11L03E                           \
    || defined TARGET_MODEL_STC11L04                            \
    || defined TARGET_MODEL_STC11L04E                           \
    || defined TARGET_MODEL_STC11L05                            \
    || defined TARGET_MODEL_STC11L05E                           \
    || defined TARGET_MODEL_STC11L08                            \
    || defined TARGET_MODEL_STC11L08X                           \
    || defined TARGET_MODEL_STC11L08XE                          \
    || defined TARGET_MODEL_STC11L16                            \
    || defined TARGET_MODEL_STC11L16X                           \
    || defined TARGET_MODEL_STC11L16XE                          \
    || defined TARGET_MODEL_STC11L20                            \
    || defined TARGET_MODEL_STC11L20X                           \
    || defined TARGET_MODEL_STC11L20XE                          \
    || defined TARGET_MODEL_STC11L32                            \
    || defined TARGET_MODEL_STC11L32X                           \
    || defined TARGET_MODEL_STC11L32XE                          \
    || defined TARGET_MODEL_STC11L40                            \
    || defined TARGET_MODEL_STC11L40X                           \
    || defined TARGET_MODEL_STC11L40XE                          \
    || defined TARGET_MODEL_STC11L48                            \
    || defined TARGET_MODEL_STC11L48X                           \
    || defined TARGET_MODEL_STC11L48XE                          \
    || defined TARGET_MODEL_STC11L52                            \
    || defined TARGET_MODEL_STC11L52X                           \
    || defined TARGET_MODEL_STC11L52XE                          \
    || defined TARGET_MODEL_STC11L56                            \
    || defined TARGET_MODEL_STC11L56X                           \
    || defined TARGET_MODEL_STC11L56XE                          \
    || defined TARGET_MODEL_STC11L60                            \
    || defined TARGET_MODEL_STC11L60X                           \
    || defined TARGET_MODEL_STC11L60XE                          \
    || defined TARGET_MODEL_STC11Lxx
#define TARGET_FAMILY_STC11F
#endif

#if defined TARGET_MODEL_STC89C516RD_                           \
    || defined TARGET_MODEL_STC89C51RC                          \
    || defined TARGET_MODEL_STC89C52RC                          \
    || defined TARGET_MODEL_STC89C53RC                          \
    || defined TARGET_MODEL_STC89C54RD_                         \
    || defined TARGET_MODEL_STC89C58RD_                         \
    || defined TARGET_MODEL_STC89C5xRC                          \
    || defined TARGET_MODEL_STC89CxRC                           \
    || defined TARGET_MODEL_STC89Cxx                            \
    || defined TARGET_MODEL_STC89LE516RD_                       \
    || defined TARGET_MODEL_STC89LE51RC                         \
    || defined TARGET_MODEL_STC89LE52RC                         \
    || defined TARGET_MODEL_STC89LE53RC                         \
    || defined TARGET_MODEL_STC89LE54RD_                        \
    || defined TARGET_MODEL_STC89LE58RD_                        \
    || defined TARGET_MODEL_STC89LExx
#define TARGET_FAMILY_STC89C
#endif


#endif /* __MODELDB_H */
